/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/confirm` | `/confirm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/join` | `/join`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/group` | `/group`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/confirm` | `/confirm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/join` | `/join`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/group` | `/group`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/confirm${`?${string}` | `#${string}` | ''}` | `/confirm${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/join${`?${string}` | `#${string}` | ''}` | `/join${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/group${`?${string}` | `#${string}` | ''}` | `/group${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/confirm` | `/confirm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/join` | `/join`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/group` | `/group`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
